### ISSUE TITLE
Doesn't work in light mode

### ISSUE THREAD

**Issue by Mara-Li** [deathau/cm-editor-syntax-highlight-obsidian#18]
Maybe I miss something in the readme ? (it's just about yonce)
The plugin only work with dark mode : 
![image](https://user-images.githubusercontent.com/30244939/118964837-3f9e2c00-b968-11eb-95bd-0c4767e377e9.png)
VS
![image](https://user-images.githubusercontent.com/30244939/118964870-47f66700-b968-11eb-91f9-80ab40650cf2.png).

Miss I something ? I will be happy to have color syntaxing with my little light theme !

**Comment by aburton-marketing** [comment]
Have you tried other light themes?

**Comment by NomarCub** [comment]
It's the same for me with the default light theme. But only found this with this python code, works fine with javascript for some reason.
![image](https://user-images.githubusercontent.com/5298006/126044314-b932e0cc-6b4a-4a81-99c9-5c8140cfc725.png)
![image](https://user-images.githubusercontent.com/5298006/126044332-33d21144-0242-4547-86e4-1cc0ce1302df.png)
