### ISSUE TITLE
Need to produce another release AKA Elixir highlighting not working

### ISSUE THREAD

**Issue by suranyami** [deathau/cm-editor-syntax-highlight-obsidian#23]
It looks like there needs to be a new release created.

Although the current version is marked as 0.1.2, the bundle is marked as 0.1.1:

<img width="431" alt="Screen Shot 2021-08-26 at 1 50 21 pm" src="https://user-images.githubusercontent.com/69984/130897979-56cd975b-dd51-49fe-b373-09d0e3b17143.png">

This means that the source code has been updated to include the `elixir` mode, but it is missing from the release files.

Here is a screen grab using the release of 0.1.2:

<img width="1532" alt="Screen Shot 2021-08-26 at 1 24 02 pm" src="https://user-images.githubusercontent.com/69984/130898217-c765dd07-2116-491a-a022-1f83d85de173.png">

<img width="627" alt="Screen Shot 2021-08-26 at 1 24 23 pm" src="https://user-images.githubusercontent.com/69984/130898244-7bc71886-2c68-4c12-ada4-a6c5e15e6421.png">

And this is the same pages, but with a checked out version of the repo and the release files copied into the plugin directory:

<img width="1556" alt="Screen Shot 2021-08-26 at 1 38 47 pm" src="https://user-images.githubusercontent.com/69984/130898320-5550d723-0af1-4d0f-b65a-2821418323d1.png">

**Comment by jzhang-brex** [comment]
I came across an issue where elixir is not properly highlighted. Spending a while in debugging lands me points me to this plugin and this issue should be the reason why it didn't work.

+1 would like to help fix this.

**Comment by suranyami** [comment]
@deathau It's been 11 months… any chance we could get this new release?

As stated above, we'd be happy to help, but unfortunately, as it stands, seems like only you can do a new release.

Happy to weigh in and see if some of the outstanding issues can be fixed, if you don't have time for it. It happens to all of us… Just add myself and @jzhang-brex  as collaborators and we'll be your minions! :-)

**Comment by jzhang-brex** [comment]
I also reached out to @deathau on Discord. Hopefully we can get a response.

**Comment by deathau** [comment]
Sorry about taking so long to getting around to this. Pushed out a release now with the elixir fix (the mode was present in 0.1.2, but it wasn't imported in main.ts)
Also, I think my build scripts are mis-labelling the zip file in the release,

**Comment by suranyami** [comment]
Thanks for that @deathau 

seems like that’s fixed things. 

Offer for assistance still stands.
