### ISSUE TITLE
Dark mode awareness

### ISSUE THREAD

**Issue by NomarCub** [deathau/cm-editor-syntax-highlight-obsidian#4]
I have YAML frontmatter in some notes. I don't have any custom CSS, and they look like this in dark mode. It's basically unreadable.

![image](https://user-images.githubusercontent.com/5298006/98539279-59a9d400-228c-11eb-9332-b28ad2d7f98b.png)

Text color is the same in light mode, where it's not a problem.
![image](https://user-images.githubusercontent.com/5298006/98539564-db016680-228c-11eb-8fd9-684d859b508e.png)

The highlighting should be either aware of your theme (at least of dark and light mode) or use colors that are readable in both dark and light mode.

**Comment by deathau** [comment]
Ah. This isn't so much dark mode awareness as it is not realizing the syntax highlighting would also apply to the frontmatter.
I do have the yoncé colour scheme built-in specifically for dark mode, but it's currently only applying to code blocks and not frontmatter.

Thanks for pointing it out. I will fix it.
