### ISSUE TITLE
help add C/C++ syntax highlight

### ISSUE THREAD

**Issue by L-Super** [deathau/cm-editor-syntax-highlight-obsidian#54]
When I switch the preview mode, the code has no syntax highlighting
![image](https://user-images.githubusercontent.com/40905056/196903405-02de2a61-e697-414a-9315-a7f237e8b8ac.png)

**Comment by L-Super** [comment]
`C++` -> `cpp` display normal
![image](https://user-images.githubusercontent.com/40905056/196904043-b298a123-5347-431f-84f4-c8723f98c1d7.png)

![image](https://user-images.githubusercontent.com/40905056/196904019-1280b232-3e10-4608-8842-ed8eed8fd50a.png)

**Comment by KenieEX** [comment]
Try: Import and Export->Reset

**Comment by Cisym** [comment]
我从你这才找到我写C++代码阅读模式全红的原因，原来```后面是CPP才可以

**Comment by L-Super** [comment]
> 我从你这才找到我写C++代码阅读模式全红的原因，原来```后面是CPP才可以

哈哈哈，我也是无意中发现的🤣
