### ISSUE TITLE
Is this plugin dead?

### ISSUE THREAD

**Issue by ravero** [deathau/cm-editor-syntax-highlight-obsidian#65]
Last commit was more than a year ago, and I don't see any responses from other issues. Is this plugin abandoned? That is sad because it's a very useful one for developers and writers.

**Comment by Taitava** [comment]
I'm not so familiar with this plugin. Obsidian seems to support syntax highlighting in code blocks nowadays. Does this plugin have some features that are missing from Obsidian? 🙂 

Edit: Syntax highlighting came to Obsidian in 0.13.6 on 2021-11-26: https://forum.obsidian.md/t/obsidian-release-v0-13-6-insider-build/27676
> - Added code syntax highlighting for source mode and live preview (including legacy editor).

**Comment by XDcedar** [comment]
~Although Obsidian supports highlighting, it is not supported in Live Preview. But this plugin does. It's still useful.~
No, I'm wrong. I just forgot to restart Obsidian. See below.

**Comment by Taitava** [comment]
> Although Obsidian supports highlighting, it is not supported in Live Preview. But this plugin does. It's still useful.

Works at least for me on native Obsidian 1.2.8.

Live preview, caret not in code block:
![kuva](https://github.com/deathau/cm-editor-syntax-highlight-obsidian/assets/13002142/c6729432-0314-49e2-9201-04ad5cddc739)

Live preview, caret in code block:
![kuva](https://github.com/deathau/cm-editor-syntax-highlight-obsidian/assets/13002142/a879d77f-7988-42c7-bb95-a314366b7cce)

This is in sandbox vault, so no community plugins are installed.

**Comment by XDcedar** [comment]
> > Although Obsidian supports highlighting, it is not supported in Live Preview. But this plugin does. It's still useful.
> 
> Works at least for me on native Obsidian 1.2.8.
> 
> Live preview, caret not in code block: ![kuva](https://user-images.githubusercontent.com/13002142/240626289-c6729432-0314-49e2-9201-04ad5cddc739.png)
> 
> Live preview, caret in code block: ![kuva](https://user-images.githubusercontent.com/13002142/240626439-a879d77f-7988-42c7-bb95-a314366b7cce.png)
> 
> This is in sandbox vault, so no community plugins are installed.

Oh you are right! I turned restricted mode on and restarted my vault, then the highlighting came back. Maybe I just forgot to restart Obsidian last time.

**Comment by Aetherinox** [comment]
The plugin still has its usefulness.

I originally used this plugin as a user until I started having performance issues in regards to larger sets of code being on a page and it causing massive delays in typing. So I've been slowly working on performance fixes to address it since the original developer seems to be MIA.  It's just a matter of free time.
