### ISSUE TITLE
Can't seem to get the plugin to work?

### ISSUE THREAD

**Issue by AnnSpec** [deathau/cm-editor-syntax-highlight-obsidian#71]
With the syntax highlighter updated and enabled, I still can't seem to get the effect to work. My code windows are still completely vanilla.

Have experienced this with several plugins, however, so it could be unrelated to the plugin and more of an Obsidian problem ?

**Comment by scrungus** [comment]
@AnnSpec i'm experiencing this whilst I have a custom theme enabled. I wonder if it is interfering?

**Comment by sascharo** [comment]
It does not work for me with the "Default" theme either.

It has a different purpose but the only highlighting plug-in that works for me is nl-syntax-highlighting: https://github.com/artisticat1/nl-syntax-highlighting

**Comment by AnnSpec** [comment]
Hey! I actually figured this one out.

when you write the ``` to indicate a code block, you have to write the name of the coding language there.

ie:

(3 ` characters) c
include <header.c>
int main(void)
{
etc
}
(3 ' characters)



hope that helps others!

**Comment by tortoo** [comment]
I have tested it several times and it seems that the plug-in has failed. No matter how I modify the styles.css file, it doesn't work. What should work is the code highlighting that comes with Obsidian, but the one that comes with it is too simple and the customizable parts are too limited. There are many things that can be modified in this plug-in, but unfortunately it cannot take effect.
