### ISSUE TITLE
Plugin no longer appears in community plugins

### ISSUE THREAD

**Issue by dkarter** [deathau/cm-editor-syntax-highlight-obsidian#83]
Not sure if anything changed in Obsidian, but this plugin no longer appears in the community plugins and was automatically(?) removed from my installed plugin list.

![CleanShot 2024-06-14 at 14 08 18@2x](https://github.com/deathau/cm-editor-syntax-highlight-obsidian/assets/551858/d8b76e80-1625-4f7b-957a-39a965373d0d)

I really hope this can be fixed because having syntax highlighting for Elixir is extremely important to me.

Thank you for all the efforts on this, and please let me know if there's any way I can help!

**Comment by ElMissas** [comment]
Same issue here, although the plugin still appears in my installed plugins list. Also, it appears that Obsidian now supports code syntax highlighting natively, but only in reading mode. I don't know if that has something to do with the plugin not appearing in community plugins.

**Comment by nielsbom** [comment]
The [Shiki plugin](https://github.com/mProjectsCode/obsidian-shiki-plugin) works as an alternative for me.

**Comment by dkarter** [comment]
Yea I’ve been using shiki it’s fantastic and actually fixes the code wrapping issue that the original code blocks have in obsidian - highly recommend it for anyone bumping into this.
